# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
gems: [jekyll-paginate]

# Setup
title:               Adam Watters
tagline:             'Web Development and Everything Else'
description:         "I'm Adam Watters, a web developer, carpenter, and occasional practicioner of the dark arts. You can find me, <a href='https://github.com/adamwatters'>on Github</a>, <a href='https://www.instagram.com/adam.watters/'>on Instagram</a>, and <a href='http://www.instructables.com/member/adamwatters/'>on Instructables.</a> Somehow I missed the boat on Twitter."
url:                 http://adamwatters.nyc
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Adam Watters
  email:             adamwatters11@gmail.com

# Custom vars
version:             1.0.0
